#app_chrome = App('C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe')
#app_chrome.open(2)
type(Key.WIN)
wait(1)
type('Outlook')
wait(1)
type(Key.ENTER)
wait(5)
type("n", Key.CTRL)
wait(2)
type(Key.LEFT, Key.WIN)
wait(2)
type("e", Key.WIN)
wait(2)
click("1695174481325")
wait(2)
type(Key.RIGHT, Key.WIN)
wait(1)
type("a", Key.CTRL)
wait(1)
xfrom = find("1695175577831")
from_location = Location(xfrom.getX(), xfrom.getY())
target = find("target")
target_location = Location(target.getX(), target.getY())
dragDrop(from_location, target_location)
##
wait(1)
location = find("email_to").right(50)
click(location);
#absolution location in the screen
#click(Location(230, 268))
type("meadlai@qq.com")
type(Key.ENTER)
wait(1)
click(Location(245, 345))
wait(1)
type('Latest CPI Files')
wait(1)
click(Location(62, 512))
wait(1)
type('Hello Boss,\n\r Attached is the latest files of Consumer Price Index Supplemental Files. \n\r :)')
wait(1)
click("1695180849998")
wait(1)
popup('All Set for you, have a good day!','Great')




